trigger:
- main

variables:
  azureSubscription: 'ac03a077-353c-4da7-9874-d5d115420f55'
  functionAppName: 'kafka-dotnet'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    cd dotnet
    dotnet restore
    dotnet build --configuration Release
    dotnet publish --configuration Release --output $(System.DefaultWorkingDirectory)/publish_output

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output'
    includeRootFolder: false
    archiveFile: $(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip
    replaceExistingArchive: true

- upload: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
  artifact: drop

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: functionAppLinux
    appName: $(functionAppName)
    package: $(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip
    deploymentMethod: runFromPackage
